version: '3.8'
services:
   mle:
       build: .
       image: mle
       restart: unless-stopped
       command: bash -c "python src/preprocess.py && python src/train.py && python src/predict.py -m LOG_REG -t func && coverage run src/unit_tests/test_preprocess.py && coverage run -a src/unit_tests/test_training.py && coverage report -m && gunicorn --bind 0.0.0.0:5000 src.web_predict:app"
       expose:
            - "5000"
       deploy:
            replicas: 1
            
   nginx-balancer:
       image: nginx
       container_name: nginx-balancer
       restart: unless-stopped
       volumes:
            - ./nginx-balancer/nginx.conf:/etc/nginx/nginx.conf:ro
       depends_on:
            - mle
       ports:
            - "5000:4000"

   nginx-html:
       image: nginx
       container_name: nginx-html
       restart: unless-stopped
       volumes:
           - ./html:/usr/share/nginx/html
       depends_on:
           - nginx-balancer
       ports:
           - "8080:80"


