version: '3.8'
services:
   mle:
       build: .
       image: mle
       restart: no
       expose:
            - "5000"
       deploy:
            replicas: 1
            
   nginx-balancer:
       image: nginx
       container_name: nginx-balancer
       restart: no
       volumes:
            - ./nginx-balancer/nginx.conf:/etc/nginx/nginx.conf:ro
       depends_on:
            - mle
       ports:
            - "5000:4000"

   nginx-html:
       image: nginx
       container_name: nginx-html
       restart: no
       volumes:
           - ./html:/usr/share/nginx/html
       depends_on:
           - nginx-balancer
       ports:
           - "8080:80"


